### ISSUE TITLE
通过memoQ安装插件后，配置了第三方翻译服务的账号信息，检测通过后，点击预翻译，发现翻译没生效，没有翻译结果

### ISSUE THREAD

**Issue by sunyouyuan** [JuchiaLu/Multi-Supplier-MT-Plugin#1]
通过memoQ（版本10.4.12）安装插件后，配置了第三方翻译服务的账号信息，检测通过后，点击预翻译，发现翻译没生效，没有翻译结果，烦请确认，vx：s1114879848

**Comment by JuchiaLu** [comment]
我正常使用，可能是你没没设置好，请参考[最佳实践图文教程](https://github.com/JuchiaLu/Multi-Supplier-MT-Plugin/blob/main/doc/BestPractice.md)中的 “二 - 10”。
