### ISSUE TITLE
Papago Support

### ISSUE THREAD

**Issue by unicode45** [JuchiaLu/Multi-Supplier-MT-Plugin#3]
It's a great MT Plugin.
Please support Papago Translation as well.
Thanks!

**Comment by JuchiaLu** [comment]
I've added PaPaGo support, but since I don't have an account, I can't test it out.

Also, according to [PaPaGo's docs](https://api.ncloud-docs.com/docs/en/ai-naver-papagonmt-translation), I couldn't find any info on its rate limits, and it doesn't seem to support batch translations or HTML tags.

**Comment by unicode45** [comment]
Thanks for your quick response!
I've just tested v1.1.1 and it works great with Papago.
Btw, I've found that error code N2MT08 which means 'text parameter exceeds max length' in Papago.
And it seems there's a limitation of text length, too. if I found detail specification, I'll let you know later.
Thanks!
