### ISSUE TITLE
关于Google 和Microsoft MT

### ISSUE THREAD

**Issue by james1016** [JuchiaLu/Multi-Supplier-MT-Plugin#4]
请问，这两个配置以后会失效吗？

**Comment by JuchiaLu** [comment]
接口取自 Edge 和 Chrome 浏览器内置的翻译接口，谷歌接口已经稳定很多年，且它会根据 IP 进行限流，所以我猜测它是默许这种行为的，配置是否失效取决于他们是否继续默许这种行为。

**Comment by james1016** [comment]
好的 谢谢！
