### ISSUE TITLE
插件警告提示如何取消

### ISSUE THREAD

**Issue by aiduhuihuang** [JuchiaLu/Multi-Supplier-MT-Plugin#6]
每次打开软件就会提示插件的不安全警告，我看您在里面提高clientDevconfig.xml文件复制到制定地方，但是我这边并没有找到
请问在哪里呢？或者有没有其他方法，谢谢
邮件972022747@qq.com

再一次感谢您

**Comment by JuchiaLu** [comment]
“插件未经过签名，每次启动 memoQ 都会询问是否加载，如果不想每次询问，需要将 ClientDevConfig.xml 放入到 %programdata%/MemoQ 目录下。”

你下载的 zip 压缩包中应该包含 ClientDevConfig.xml 文件，直接按“Win + R”或在文件管理器上方路径处输入 %programdata%/MemoQ，回车进入目录后将 ClientDevConfig.xml 文件复制到目录下。

**Comment by aiduhuihuang** [comment]
感谢，感谢，已经找到

**Comment by aiduhuihuang** [comment]
这个是所有的插件都不弹窗，有没有办法控制具体的插件不弹窗。比如，自己的插件名，A,安装了一个B插件，可以控制具体不弹窗提示A或者B未不安全警告弹窗。谢谢。

**Comment by JuchiaLu** [comment]
据我所知，无法控制仅放行某一款插件。
