### ISSUE TITLE
最近发现启用这个插件后，memoa会闪退

### ISSUE THREAD

**Issue by Jjjmaes** [JuchiaLu/Multi-Supplier-MT-Plugin#7]
前面一直很稳定，现在启用这个插件后会闪退 版本  10.5

**Comment by JuchiaLu** [comment]
根据 memoQ SDK 文档， 它进行了如下更改：

| Date         | Version | Who  | Change                                                       |
| ------------ | ------- | ---- | ------------------------------------------------------------ |
| Jan 26, 2024 | 10.6    | NT   | Using  Polly as external package, Kilgray.Utils package is deprecated |
| Jan 26, 2024 | 10.6    | NT   | MaxDegreeOfParallelism  property introduction                |
| May 27, 2024 | 11.1    | BT   | Implement  MT parallelism check in Dummy MT Plugin, update MT SDK and documentation, a  few fixes |

10.5 版本是 2024 年 2 月 26 日发布的，可能是由于以上更改导致，我稍后会更进。

**Comment by JuchiaLu** [comment]
抽空更新了下插件，并测试了下这个问题，没能复现你这个问题，可能和你的电脑环境有关。
![](https://github.com/user-attachments/assets/1744912e-b088-413a-a7aa-a11dc08a00e2)
