### ISSUE TITLE
Claude API - Checked Fail!

### ISSUE THREAD

**Issue by Saeedr85** [JuchiaLu/Multi-Supplier-MT-Plugin#9]
![Capture](https://github.com/user-attachments/assets/80b8d44d-d5b1-4604-a73c-5f585693c7d2)

**Comment by Saeedr85** [comment]
Dear Dev,

I wanted to express my sincere gratitude for creating this exceptional plugin. Your hard work and dedication are truly commendable.

I've obtained an API key from Anthropic and have attempted to implement it. Unfortunately, I've encountered some difficulties in getting it to work properly. I was wondering if you might have any suggestions or troubleshooting tips to help resolve this issue?

Thank you for your time and assistance.

**Comment by JuchiaLu** [comment]
Since I don't have Claude's API Key, I can't confirm if my code implementation is correct. If possible, you could provide a temporary API Key to the email address I'll provide in my next comment. After I confirm the code implementation is correct, you can destroy it. In the next version, I'll add a feature to write error messages details to log file.

**Comment by JuchiaLu** [comment]
juchialu@gmail.com

**Comment by Saeedr85** [comment]
Done,

**Comment by JuchiaLu** [comment]
fixed

[Claude Support Test.zip](https://github.com/user-attachments/files/16559215/Claude.Support.Test.zip)

**Comment by Saeedr85** [comment]
Really thank you,

**Comment by Saeedr85** [comment]
Can you add an external link for editting the prompt instantly out of the memoq interface.

**Comment by JuchiaLu** [comment]
Due to memoQ SDK limitations, the plugin cannot modify any memoQ GUI interface outside the configuration interface. You can install the plugin multiple times ("multi install"), with each plugin instance using a separate Prompt.

**Comment by Saeedr85** [comment]
Thank you for the clarification.

**Comment by JuchiaLu** [comment]
Or have I misunderstood your meaning? You're not talking about modifying the memoQ GUI interface, but providing a separate, always-open GUI interface to modify the Prompt in real-time. If that's the case, it can be done.

**Comment by Saeedr85** [comment]
Exactly, that is what I meant.

**Comment by Saeedr85** [comment]
Unfortunately, The problem has not been solved. I can not add the API of Anthropic.
Thanks for your assistance

**Comment by JuchiaLu** [comment]
I'm sure I've fixed it. Perhaps it's because you destroyed the previously saved API key and haven't used a new API key, or maybe you haven't overwritten the old plugin DLL file with the new one?

**Comment by Saeedr85** [comment]
I have removed all the plugin files from the addins directory.

**Comment by JuchiaLu** [comment]
Please provide another temporary API key to my email address so I can test again to see what happened.

**Comment by Saeedr85** [comment]
Done,

**Comment by JuchiaLu** [comment]
![](https://github.com/user-attachments/assets/83bad31a-650c-4dda-bf15-54a7607726bd)

**Comment by JuchiaLu** [comment]
you can use [this](https://emn178.github.io/online-tools/md5_checksum.html) website check the new dll file MD5

![](https://github.com/user-attachments/assets/9911e6ba-9104-49bc-a305-8b354f0bf1e2)

**Comment by Saeedr85** [comment]
I will check

**Comment by Saeedr85** [comment]
5aa291309aca85fe47a97d58f93f3857
it is the same

**Comment by Saeedr85** [comment]
Not work!

**Comment by Saeedr85** [comment]
Shall I install any supporting libraries?

**Comment by JuchiaLu** [comment]
No, I only made minor changes to the code. I'm also confused why it can't pass the check.

**Comment by Saeedr85** [comment]
I will try to remove the plugin completely, and reinstall it.

**Comment by Saeedr85** [comment]
Worth to mention,
Our country is blocked from using claude.
So, i always use psiphon to access AI models.

Does this suggest a solution for the problem

**Comment by JuchiaLu** [comment]
Yes, Claude blocks API access from certain IPs, especially public IPs used by many people.

**Comment by Saeedr85** [comment]
Kindly,
Do you have any suggestions for solving this u

**Comment by Saeedr85** [comment]
Kindly,
Do you have any suggestions for solving this issue?

**Comment by Saeedr85** [comment]
I have access to Anthropic site through VPN. While I get the error message when accessing to the API via the plugin!
Is there something could be edited in the memoq's settings?

**Comment by JuchiaLu** [comment]
Depends on how your VPN works:
- If it's network card-based, it will proxy all traffic data without any additional settings
- If it's based on system proxy, you'll need to set memoQ to "Use system settings"
- If it provides a proxy address, you'll need to set memoQ to "Custom proxy settings"

![](https://github.com/user-attachments/assets/060f4c36-e48b-451c-87e8-e1216fe6e1bb)

![](https://github.com/user-attachments/assets/e4b7d293-aef5-41cf-b9a7-d6cfc74323a9)

**Comment by Saeedr85** [comment]
It works,
I changed the settings to "Use System Settings"

Thank you very much
